const dictionary = {
  en: {
    home: {
      title: 'Welcome to Mazz Bar!',
      description: [
        '1. Select your language.',
        '2. See if the visitor is unknown or not.',
        '3. See the picture of the character.',
        '4. Print information related to it.',
        '5. Change Your Settings',
      ],
      language_description: 'Please select your language:',
    },
    loading: 'Loading...',
    history: {
      title: 'History',
      clear: 'Clear history',
    },
    buttons: {
      random: 'Random',
      print: 'Print',
      show: 'Show',
      hide: 'Hide',
      back: 'Back',
      procced: 'Procced',
      settings: 'Settings',
    },
    character: {
      name: 'Name',
      height: 'Height',
      mass: 'Mass',
      gender: {
        title: 'Gender',
        type: {
          male: 'Male',
          female: 'Female',
          'n/a': 'Not Available',
        },
      },
      eye: {
        title: 'Eye Color',
        color: {
          blue: 'Blue',
          'blue-gray': 'Blue Gray',
          brown: 'Brown',
          yellow: 'Yellow',
          red: 'Red',
          black: 'Black',
          orange: 'Orange',
          hazel: 'Hazel',
          pink: 'Pink',
          unknown: 'Unknown',
          'red, blue': 'Red and Blue',
          gold: 'Gold',
          'green, yellow': 'Green and Yellow',
          white: 'White',
          dark: 'Dark',
        },
      },
      hair: {
        title: 'Hair',
        color: {
          blond: 'Blond',
          'n/a': 'Not Available',
          none: 'None',
          brown: 'Brown',
          'brown, grey': 'Brown, Grey',
          black: 'Black',
          'auburn, white': 'Auburn, White',
          'auburn, grey': 'Auburn, Grey',
          white: 'White',
          grey: 'Grey',
          auburn: 'Auburn',
          blonde: 'Blonde',
          unknown: 'Unknown',
        },
      },
    },
  },
  pt: {
    home: {
      title: 'Bem vindo ao Mazz Bar!',
      description: [
        '1. Selecione sua linguagem.',
        '2. Veja se o visitante é desconhecido ou não.',
        '3. Veja a foto do personagem.',
        '4. Imprima informações relacionadas a ele.',
        '5. Altere suas configurações',
      ],
      language_description: 'Favor selecionar sua lingua:',
    },
    loading: 'Carregando...',
    history: {
      title: 'Histórico',
      clear: 'Limpar histórico',
    },
    buttons: {
      random: 'Randômico',
      print: 'Imprimir',
      show: 'Mostrar imagem',
      back: 'Voltar',
      hide: 'Esconder imagem',
      procced: 'Avançar',
      settings: 'Configurações',
    },
    character: {
      name: 'Nome',
      height: 'Altura',
      mass: 'Peso',
      gender: {
        title: 'Gênero',
        type: {
          male: 'Masculino',
          female: 'Feminino',
          'n/a': 'Não disponível',
        },
      },
      eye: {
        title: 'Cor dos olhos',
        color: {
          blue: 'Azul',
          brown: 'Castanho',
          yellow: 'Amarelo',
          red: 'Vermelho',
          'blue-gray': 'Cinza Azul',
          black: 'Preto',
          orange: 'Laranja',
          hazel: 'Avelã',
          pink: 'Rosa',
          unknown: 'Desconhecido',
          'red, blue': 'Vermelho-azulado',
          gold: 'Ouro',
          'green, yellow': 'Verde-amarelado',
          white: 'Branco',
          dark: 'Sombrio',
        },
      },
      hair: {
        title: 'Cor do cabelo',
        color: {
          blond: 'Loiro',
          'n/a': 'Indisponivel',
          none: 'Sem cabelo',
          brown: 'Marrom',
          'brown, grey': 'Marrom acinzentado',
          black: 'Preto',
          'auburn, white': 'Castanho Claro',
          'auburn, grey': 'Castanho Cinzento',
          white: 'Branco',
          grey: 'Cinzendo',
          auburn: 'Castanho',
          blonde: 'Loira',
          unknown: 'Desconhecido',
        },
      },
    },
  },
  es: {
    home: {
      title: 'Bienvenido al Mazz Bar!',
      description: [
        '1. Seleccione su idioma.',
        '2. Vea si el visitante es desconocido o no.',
        '3. Ver la imagen del personaje.',
        '4. Imprima información relacionada con ella.',
        '5. Cambie su configuración',
      ],
      language_description: 'Por favor define tu idioma:',
    },
    loading: 'Cargando...',
    history: {
      title: 'Historico',
      clear: 'Limpiar historico',
    },
    buttons: {
      random: 'Al azar',
      print: 'Imprimir',
      show: 'Mostrar imagem',
      back: 'Retorno',
      hide: 'Ocultar imagem',
      procced: 'Proceder',
      settings: 'Ajustes',
    },
    character: {
      name: 'Nombre',
      height: 'Altura',
      mass: 'Masa',
      gender: {
        title: 'Género',
        type: {
          male: 'Masculino',
          female: 'Femenino',
          'n/a': 'No disponible',
        },
      },
      hair: {
        title: 'Cabello',
        color: {
          blond: 'Rubio',
          'n/a': 'No disponible',
          none: 'Sin pelo',
          brown: 'Marrón',
          'brown, grey': 'Marrón Gris',
          black: 'Negro',
          'auburn, white': 'Castaño Blanco',
          'auburn, grey': 'Castaño Rojizo',
          white: 'Blanco',
          grey: 'Rojizo',
          auburn: 'Castaño',
          blonde: 'Rubia',
          unknown: 'Desconocido',
        },
      },
      eye: {
        title: 'Color de los ojos',
        color: {
          blue: 'Azul',
          brown: 'Marrón',
          yellow: 'Amarillo',
          red: 'Rojo',
          'blue-gray': 'Azul Gris',
          black: 'Negro',
          orange: 'Naranja',
          hazel: 'Avellana',
          pink: 'Rosa',
          unknown: 'Desconocido',
          'red, blue': 'Rojo-azulado',
          gold: 'Oro',
          'green, yellow': 'Verde-amarillento',
          white: 'Blanco',
          dark: 'Oscuro',
        },
      },
    },
  },
};

export default dictionary;
